TAJO-2125: Detect default java binary, if JAVA_HOME is not set.

diff --git a/tajo-dist/src/main/bin/tajo b/tajo-dist/src/main/bin/tajo
--- a/tajo-dist/src/main/bin/tajo
+++ b/tajo-dist/src/main/bin/tajo
@@ -105,18 +105,29 @@ if [ "$COMMAND" == "datanode" ] && [ "$EUID" -eq 0 ] && [ -n "$TAJO_SECURE_DN_US
   starting_secure_dn="true"
 fi
 
-# some Java parameters
-if [ "$JAVA_HOME" != "" ]; then
-  #echo "run java in $JAVA_HOME"
-  JAVA_HOME=$JAVA_HOME
-fi
-  
-if [ "$JAVA_HOME" = "" ]; then
-  echo "Error: JAVA_HOME is not set."
-  exit 1
+# Attempt to set JAVA_HOME if it is not set
+if [[ -z $JAVA_HOME ]]; then
+  # On OSX use java_home (or /Library for older versions)
+  if [ "Darwin" == "$(uname -s)" ]; then
+    if [ -x /usr/libexec/java_home ]; then
+      export JAVA_HOME=($(/usr/libexec/java_home))
+    else
+      export JAVA_HOME=(/Library/Java/Home)
+    fi
+  fi
 fi
 
-JAVA=$JAVA_HOME/bin/java
+if [[ -z $JAVA_HOME ]]; then
+  if [ `command -v java` ]; then
+    JAVA="java"
+  else
+    echo "Error: JAVA_HOME is not set and could not be found." 1>&2
+    exit 1
+  fi
+else
+  JAVA=$JAVA_HOME/bin/java
+fi
+
 JAVA_TAJO_MASTER_HEAP_MAX=-Xmx1000m 
 JAVA_WORKER_HEAP_MAX=-Xmx5000m
 JAVA_QUERYMASTER_HEAP_MAX=-Xmx1000m
